# Generated by Django 5.1.5 on 2025-08-18 17:32

import ckeditor.fields
import django.db.models.deletion
import mptt.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(choices=[('solar_panel', 'Solar Panel'), ('inverter', 'Inverter'), ('battery', 'Battery'), ('mounting', 'Mounting System'), ('cable', 'Cables & Wiring'), ('monitoring', 'Monitoring Equipment'), ('accessory', 'Accessories')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('description', ckeditor.fields.RichTextField()),
                ('features', models.JSONField(blank=True, default=list)),
                ('applications', models.TextField(blank=True)),
                ('power_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Power in Watts', max_digits=8, null=True)),
                ('efficiency', models.DecimalField(blank=True, decimal_places=2, help_text='Efficiency percentage', max_digits=5, null=True)),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('current', models.CharField(blank=True, max_length=50)),
                ('dimensions', models.CharField(blank=True, help_text='L x W x H', max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in KG', max_digits=8, null=True)),
                ('operating_temperature', models.CharField(blank=True, max_length=50)),
                ('warranty_years', models.IntegerField(blank=True, null=True)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_order_quantity', models.IntegerField(default=1)),
                ('track_quantity', models.BooleanField(default=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('allow_backorders', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('discontinued', 'Discontinued'), ('out_of_stock', 'Out of Stock')], default='active', max_length=20)),
                ('show_to_customers', models.BooleanField(default=False, help_text='Display this product on the customer-facing website')),
                ('customer_inquiry_only', models.BooleanField(default=False, help_text='Show product but require inquiry for pricing (hide prices)')),
                ('installation_manual', models.FileField(blank=True, null=True, upload_to='manuals/')),
                ('datasheet', models.FileField(blank=True, null=True, upload_to='datasheets/')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('manual', 'Installation Manual'), ('datasheet', 'Datasheet'), ('warranty', 'Warranty Document'), ('certificate', 'Certificate'), ('brochure', 'Brochure'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='product_documents/')),
                ('description', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'featured'], name='products_pr_status_4ba6ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'category'], name='products_pr_product_a9da79_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together={('product', 'user')},
        ),
    ]
