# Generated by Django 5.0.7 on 2025-09-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voltage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
