# Generated by Django 5.0.7 on 2025-09-12 08:15

import apps.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_voltage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, help_text='Accepted format: PDF (max 10MB)', null=True, upload_to=apps.products.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), apps.products.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_manual',
            field=models.FileField(blank=True, help_text='Accepted formats: PDF, DOC, DOCX (max 10MB)', null=True, upload_to=apps.products.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.products.models.validate_file_size]),
        ),
    ]
