# Generated by Django 5.1.5 on 2025-09-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_datasheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-solar-panel')", max_length=50),
        ),
    ]
