# Generated by Django 5.1.5 on 2025-09-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productcategory_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='icon',
            field=models.CharField(default='fas fa-box', help_text="Font Awesome icon class (e.g., 'fas fa-solar-panel')", max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
