# Generated by Django 5.1.5 on 2025-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productcategory_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='power_rating_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Power in KVA (optional alternative rating)', max_digits=8, null=True),
        ),
    ]
