# Generated by Django 5.1.5 on 2025-08-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=50)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business'), ('government', 'Government'), ('ngo', 'NGO')], default='individual', max_length=20)),
                ('monthly_consumption', models.DecimalField(decimal_places=2, help_text='kWh per month', max_digits=10)),
                ('average_monthly_bill', models.DecimalField(decimal_places=2, help_text='KES', max_digits=10)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('roof_type', models.CharField(choices=[('iron_sheets', 'Iron Sheets'), ('tiles', 'Tiles'), ('concrete', 'Concrete'), ('asbestos', 'Asbestos')], default='iron_sheets', max_length=20)),
                ('roof_area', models.DecimalField(decimal_places=2, help_text='Square meters', max_digits=8)),
                ('shading_issues', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('system_type', models.CharField(choices=[('grid_tied', 'Grid-Tied System'), ('off_grid', 'Off-Grid System'), ('hybrid', 'Hybrid System'), ('backup', 'Backup Power System')], max_length=20)),
                ('system_capacity_range', models.CharField(help_text='e.g., 5-10 kW', max_length=50)),
                ('template_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('quotation_type', models.CharField(choices=[('product_sale', 'Product Sale'), ('installation', 'Installation Service'), ('maintenance', 'Maintenance Contract'), ('consultation', 'Consultation Service'), ('custom_solution', 'Custom Solar Solution')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('converted', 'Converted to Sale')], default='draft', max_length=20)),
                ('system_type', models.CharField(choices=[('grid_tied', 'Grid-Tied System'), ('off_grid', 'Off-Grid System'), ('hybrid', 'Hybrid System'), ('backup', 'Backup Power System')], max_length=20)),
                ('system_capacity', models.DecimalField(decimal_places=2, help_text='kW', max_digits=8)),
                ('estimated_generation', models.DecimalField(decimal_places=2, help_text='kWh per month', max_digits=10)),
                ('installation_complexity', models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], default='simple', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_annual_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payback_period_months', models.IntegerField()),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financing_available', models.BooleanField(default=False)),
                ('financing_options', models.JSONField(blank=True, default=dict)),
                ('validity_days', models.IntegerField(default=30)),
                ('valid_until', models.DateField()),
                ('payment_terms', models.TextField(default='50% deposit, 50% on completion')),
                ('delivery_time', models.CharField(default='2-4 weeks', max_length=100)),
                ('warranty_terms', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotations.customer')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('visit', 'Site Visit'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('notes', models.TextField()),
                ('scheduled_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='quotations.quotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['quotation_number'], name='quotations__quotati_d2f33a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['status', 'created_at'], name='quotations__status_aacf5a_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['salesperson', 'status'], name='quotations__salespe_64ef89_idx'),
        ),
    ]
