# Generated by Django 5.0.7 on 2025-08-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_customer_last_purchase_date_customer_loyalty_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='average_monthly_bill',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='monthly_consumption',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kWh per month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='roof_area',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Square meters', max_digits=8),
        ),
    ]
