# Generated by Django 5.1.5 on 2025-11-07 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotation_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='salesperson',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
