# Generated by Django 5.1.5 on 2025-11-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_add_salesperson_column'),
    ]

    operations = [


        migrations.AddField(
            model_name='quotation',
            name='system_capacity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kW', max_digits=8),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_generation',
            field=models.DecimalField(decimal_places=2, default=0, help_text='kWh per month', max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='installation_complexity',
            field=models.CharField(choices=[('simple', 'Simple'), ('moderate', 'Moderate'), ('complex', 'Complex')], default='simple', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_annual_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payback_period_months',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='financing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='financing_options',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quotation',
            name='validity_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(default='2025-12-07'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(default='50% deposit, 50% on completion'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_time',
            field=models.CharField(default='2-4 weeks', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='warranty_terms',
            field=models.TextField(default='25-year panel performance warranty, 12-year product warranty, 10-year inverter warranty, 5-year installation warranty'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
