# Generated by Django 5.1.5 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0007_add_missing_quotation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
