# Generated by Django 5.1.5 on 2025-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0008_add_remaining_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='estimated_monthly_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
