# Generated by Django 5.1.5 on 2025-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0009_add_estimated_monthly_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='estimated_annual_savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
