# Generated by Django 5.1.5 on 2025-11-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0010_add_estimated_annual_savings'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payback_period_months',
            field=models.IntegerField(default=120),
        ),
    ]
