# Generated by Django 5.1.5 on 2025-11-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0011_add_payback_period_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=5),
        ),
    ]
