# Generated by Django 5.1.5 on 2025-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0012_add_roi_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='financing_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='financing_options',
            field=models.JSONField(blank=True, default=dict),
        ),

        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(default='50% deposit, 50% on completion'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_time',
            field=models.CharField(default='2-4 weeks', max_length=100),
        ),
        migrations.AddField(
            model_name='quotation',
            name='warranty_terms',
            field=models.TextField(default='25-year panel performance warranty, 12-year product warranty, 10-year inverter warranty, 5-year installation warranty'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
    ]
