# Generated by Django 5.1.5 on 2025-11-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0013_add_all_remaining_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(default='50% deposit, 50% on completion'),
        ),
    ]
