# Generated by Django 5.1.5 on 2025-11-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0014_add_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_time',
            field=models.CharField(default='2-4 weeks', max_length=100),
        ),
    ]
