# Generated by Django 5.1.5 on 2025-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0015_add_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='warranty_terms',
            field=models.TextField(default='25-year panel performance warranty, 12-year product warranty, 10-year inverter warranty, 5-year installation warranty'),
        ),
    ]
