# Generated by Django 5.1.5 on 2025-11-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0016_add_warranty_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
