# Generated by Django 5.1.5 on 2025-11-07 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0017_add_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='estimated_annual_savings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='estimated_generation',
            field=models.DecimalField(decimal_places=2, help_text='kWh per month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='estimated_monthly_savings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='payback_period_months',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='salesperson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='system_capacity',
            field=models.DecimalField(decimal_places=2, help_text='kW', max_digits=8),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='warranty_terms',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='QuotationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('system_type', models.CharField(choices=[('grid_tied', 'Grid-Tied System'), ('off_grid', 'Off-Grid System'), ('hybrid', 'Hybrid System'), ('backup', 'Backup Power System'), ('not_sure', 'Not Sure - Please Advise')], default='not_sure', max_length=20)),
                ('system_requirements', models.TextField(help_text='Detailed description of the system requirements')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated budget in KES (optional)', max_digits=12, null=True)),
                ('location', models.CharField(help_text='City/Location', max_length=100)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('other', 'Other')], default='residential', max_length=50)),
                ('roof_access', models.CharField(choices=[('easy', 'Easy Access'), ('difficult', 'Difficult Access'), ('limited', 'Limited Access'), ('not_sure', 'Not Sure')], default='not_sure', max_length=50)),
                ('urgency', models.CharField(choices=[('low', 'Low - No Rush'), ('medium', 'Medium - Within 1-2 weeks'), ('high', 'High - Urgent (within 3-5 days)'), ('critical', 'Critical - ASAP')], default='medium', max_length=20)),
                ('preferred_contact_time', models.CharField(blank=True, help_text="Preferred time for contact (e.g., 'Morning', 'Afternoon')", max_length=100)),
                ('status', models.CharField(choices=[('new', 'New Request'), ('reviewed', 'Under Review'), ('contacted', 'Contact Initiated'), ('quotation_created', 'Quotation Created'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('estimated_completion_days', models.IntegerField(default=3, help_text='Estimated days to complete the quotation')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal processing notes')),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from customer')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to process this request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='quotations__status_463dca_idx'), models.Index(fields=['email'], name='quotations__email_db49f3_idx'), models.Index(fields=['assigned_to', 'status'], name='quotations__assigne_4d9c72_idx')],
            },
        ),
    ]
