# Generated by Django 5.1.5 on 2025-08-18 17:32

import apps.projects.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('quotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('residential', 'Residential Installation'), ('commercial', 'Commercial Installation'), ('industrial', 'Industrial Installation'), ('utility', 'Utility Scale'), ('maintenance', 'Maintenance Project'), ('consultation', 'Consultation')], max_length=20)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('planning', 'Planning'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('testing', 'Testing & Commissioning'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='lead', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('system_type', models.CharField(choices=[('grid_tied', 'Grid-Tied System'), ('off_grid', 'Off-Grid System'), ('hybrid', 'Hybrid System'), ('backup', 'Backup Power System')], max_length=20)),
                ('system_capacity', models.DecimalField(decimal_places=2, help_text='kW', max_digits=8)),
                ('estimated_generation', models.DecimalField(decimal_places=2, help_text='kWh per month', max_digits=10)),
                ('installation_address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('site_access_notes', models.TextField(blank=True)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField()),
                ('target_completion', models.DateField()),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('duration_days', models.IntegerField(help_text='Estimated duration in days')),
                ('completion_percentage', models.IntegerField(default=0)),
                ('safety_requirements', models.TextField(blank=True)),
                ('quality_standards', models.TextField(blank=True)),
                ('permits_required', models.JSONField(blank=True, default=list)),
                ('site_survey_report', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('installation_drawings', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('completion_certificate', models.FileField(blank=True, null=True, upload_to='project_documents/')),
                ('featured_image', models.ImageField(blank=True, help_text='Main project image displayed on website', null=True, upload_to=apps.projects.models.project_image_upload_path)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='quotations.customer')),
                ('installation_team', models.ManyToManyField(blank=True, related_name='installation_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.quotation')),
                ('salesperson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('site_survey', 'Site Survey'), ('design', 'System Design'), ('permit', 'Permit'), ('invoice', 'Invoice'), ('receipt', 'Receipt'), ('photo', 'Progress Photo'), ('report', 'Report'), ('certificate', 'Certificate'), ('warranty', 'Warranty'), ('manual', 'User Manual'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Visible to client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('equipment', 'Equipment'), ('labor', 'Labor'), ('transport', 'Transportation'), ('permits', 'Permits & Licenses'), ('subcontractor', 'Subcontractor'), ('overhead', 'Overhead'), ('other', 'Other')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='project_receipts/')),
                ('approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.budgetcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('payment_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('site_survey', 'Site Survey'), ('design', 'System Design'), ('permits', 'Permits & Approvals'), ('procurement', 'Equipment Procurement'), ('delivery', 'Equipment Delivery'), ('installation', 'Installation'), ('electrical', 'Electrical Work'), ('testing', 'Testing & Commissioning'), ('documentation', 'Documentation'), ('training', 'Customer Training'), ('handover', 'Project Handover')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='task_attachments/')),
                ('assigned_team', models.ManyToManyField(blank=True, related_name='team_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, to='projects.projecttask')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['start_date', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal update, not shared with client')),
                ('photos', models.FileField(blank=True, null=True, upload_to='project_updates/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_number'], name='projects_pr_project_338cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'priority'], name='projects_pr_status_d9e5a3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_manager', 'status'], name='projects_pr_project_980913_idx'),
        ),
    ]
