# Generated by Django 5.1.5 on 2025-09-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_facebook_url_user_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=True, help_text='Whether user has changed from temporary password'),
        ),
    ]
