# Generated by Django 5.1.5 on 2025-09-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('director', 'Director'), ('manager', 'Manager'), ('sales_manager', 'Sales Manager'), ('sales_person', 'Sales Person'), ('project_manager', 'Project Manager'), ('inventory_manager', 'Inventory Manager'), ('cashier', 'Cashier'), ('customer', 'Customer'), ('technician', 'Technician')], default='customer', max_length=20),
        ),
    ]
