# Generated by Django 5.1.6 on 2025-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutbanner_aboutsection_achievement_contactsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Subscriber', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='description',
            field=models.TextField(default='Stay updated with our latest news and offers.'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated list of interests', max_length=255),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='title',
            field=models.CharField(default='Subscribe to Our Newsletter', max_length=200),
        ),
    ]
