# Generated by Django 5.1.6 on 2025-03-17 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_certification_faqitem_policypage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('quote', 'Quote Request'), ('contact', 'Contact Form'), ('order', 'New Order'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='product_interest',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='logo',
            field=models.ImageField(blank=True, help_text='Recommended size: 400x300 pixels or smaller. Images will be resized automatically.', upload_to='certifications/'),
        ),
        migrations.CreateModel(
            name='QuoteFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('follow_up_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.quoterequest')),
            ],
            options={
                'ordering': ['-follow_up_date'],
            },
        ),
    ]
