# Generated by Django 5.1.7 on 2025-04-14 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adminnotification_quoterequest_product_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
