# Generated by Django 5.1.7 on 2025-04-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newsletter_subscribed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
