# Generated by Django 5.1.5 on 2025-08-18 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_essential', models.BooleanField(default=False, help_text='Essential cookies cannot be disabled')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Cookie Category',
                'verbose_name_plural': 'Cookie Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CookieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField(help_text='What this cookie is used for')),
                ('duration', models.CharField(help_text='How long the cookie lasts', max_length=100)),
                ('third_party', models.BooleanField(default=False, help_text='Is this a third-party cookie?')),
                ('provider', models.CharField(blank=True, help_text='Who sets this cookie', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='core.cookiecategory')),
            ],
            options={
                'verbose_name': 'Cookie Detail',
                'verbose_name_plural': 'Cookie Details',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Anonymous identifier for non-logged users', max_length=64)),
                ('essential_consent', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('analytics_consent', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('marketing_consent', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('preferences_consent', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('social_consent', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('consent_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'ordering': ['-consent_date'],
                'unique_together': {('user', 'identifier')},
            },
        ),
    ]
