# Generated by Django 5.1.5 on 2025-09-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cookiecategory_cookiedetail_cookieconsent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('system', 'System'), ('user', 'User'), ('security', 'Security'), ('error', 'Error')], default='system', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='message',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metric',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
