# Generated by Django 5.1.5 on 2025-09-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('cookie_policy', 'Cookie Policy'), ('disclaimer', 'Disclaimer'), ('refund_policy', 'Refund Policy'), ('data_deletion', 'Data Deletion')], max_length=20, unique=True),
        ),
    ]
