# Generated by Django 5.1.5 on 2025-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_legaldocument_document_type'),
    ]
    # Duplicate of 0005_add_backup_timestamp.py - no-op to avoid applying the same schema change twice.
    operations = [
        # Intentionally empty: schema change handled by 0005_add_backup_timestamp.py
    ]
