# Generated by Django 5.1.5 on 2025-09-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_legaldocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='last_backup_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time of the last successful system backup', null=True),
        ),
    ]
