# Generated by Django 5.1.5 on 2025-10-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_backup_timestamp'),
        ('core', '0005_companysettings_last_backup_datetime'),
    ]

    operations = [
    ]
