# Generated by Django 5.2.8 on 2025-11-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20251008_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='hero_disclaimer',
            field=models.TextField(blank=True, default='Professional site assessment and 10-year warranty included. Payback period: 3-5 years.'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='hero_featured_customers_count',
            field=models.CharField(default='500+', help_text='Number shown in hero and testimonials', max_length=50),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='testimonial_section_subtitle',
            field=models.TextField(blank=True, default='Real stories from real customers who chose solar energy with {{ company.name }}'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='testimonial_section_title',
            field=models.CharField(blank=True, default='What Our Customers Say', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='urgency_banner_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable urgency banner'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='urgency_banner_end_date',
            field=models.DateField(blank=True, help_text='End date for the urgency banner', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='urgency_banner_text',
            field=models.CharField(blank=True, default='Limited Time: Get FREE installation assessment this month!', max_length=200),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Join 500+ Kenya families who cut electricity bills by 75% with professional solar installations. Complete system design, financing & installation - starts from KES 250,000.'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Save KES 150,000+ on Your First Year - Go Solar Today!', max_length=200),
        ),
    ]
