# Generated by Django 5.2.8 on 2025-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companysettings_hero_disclaimer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='cities_served',
            field=models.CharField(default='20+', help_text='Number of cities/areas served', max_length=10),
        ),
    ]
