# Generated by Django 5.2.8 on 2025-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companysettings_cities_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='co2_saved_tons',
            field=models.CharField(default='450+', help_text='Total CO2 saved in tons', max_length=10),
        ),
    ]
