# Generated by Django 5.2.8 on 2025-11-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_co2_saved_tons_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(help_text='Full name of the testimonial author', max_length=100)),
                ('author_initials', models.CharField(default='?', help_text="Initials for avatar (e.g., 'MK' for Mohammed K.)", max_length=2)),
                ('location', models.CharField(blank=True, help_text="Location (e.g., 'Westlands, Nairobi')", max_length=100)),
                ('quote', models.TextField(help_text='Testimonial quote text')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('is_featured', models.BooleanField(default=True, help_text='Display this testimonial on the homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
