# Generated by Django 5.2.8 on 2025-12-01 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyanHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the holiday', max_length=100, unique=True)),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('religious', 'Religious Holiday'), ('cultural', 'Cultural Holiday')], default='national', max_length=20)),
                ('date_type', models.CharField(choices=[('fixed', 'Fixed Date'), ('variable', 'Variable Date'), ('calculated', 'Calculated Date')], default='fixed', max_length=20)),
                ('fixed_month', models.IntegerField(blank=True, help_text='Month (1-12) for fixed holidays', null=True)),
                ('fixed_day', models.IntegerField(blank=True, help_text='Day for fixed holidays', null=True)),
                ('lead_time_days', models.IntegerField(default=14, help_text='Days before holiday to start showing offers')),
                ('duration_days', models.IntegerField(default=7, help_text='How many days the holiday period lasts')),
                ('description', models.TextField(blank=True, help_text='Description of the holiday')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this holiday for offers')),
                ('emoji', models.CharField(blank=True, help_text='Emoji to represent the holiday', max_length=10)),
            ],
            options={
                'verbose_name': 'Kenyan Holiday',
                'verbose_name_plural': 'Kenyan Holidays',
                'ordering': ['fixed_month', 'fixed_day', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_text', models.CharField(help_text='Text to display in the banner', max_length=200)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 10.00 for 10%)', max_digits=5, null=True)),
                ('discount_description', models.TextField(blank=True, help_text='Detailed discount information')),
                ('special_benefits', models.TextField(blank=True, help_text='Additional benefits or terms')),
                ('custom_lead_days', models.IntegerField(blank=True, help_text="Override holiday's default lead time", null=True)),
                ('custom_duration_days', models.IntegerField(blank=True, help_text="Override holiday's default duration", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this offer')),
                ('priority', models.IntegerField(default=1, help_text='Higher priority wins for overlapping holidays')),
                ('order', models.IntegerField(default=0, help_text='Display order for multiple offers')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.kenyanholiday')),
            ],
            options={
                'verbose_name': 'Holiday Offer',
                'verbose_name_plural': 'Holiday Offers',
                'ordering': ['-priority', 'order', '-created_at'],
            },
        ),
    ]
