# Generated by Django 5.2.8 on 2025-12-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_kenyan_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the area (e.g., Nairobi, Kiambu)', max_length=100)),
                ('area_type', models.CharField(choices=[('county', 'County'), ('town', 'Town/City'), ('region', 'Region')], default='county', max_length=20)),
                ('coverage_type', models.CharField(choices=[('primary', 'Primary Service Area'), ('extended', 'Extended Service Area'), ('planned', 'Planned Expansion')], default='primary', max_length=20)),
                ('county', models.CharField(blank=True, help_text='County name if applicable', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional information about service in this area')),
                ('estimated_response_time', models.CharField(blank=True, help_text='Estimated response/installation time', max_length=50)),
                ('contact_person', models.CharField(blank=True, help_text='Local contact person', max_length=100)),
                ('contact_phone', models.CharField(blank=True, help_text='Local contact phone', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this area is currently serviced')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Service Area',
                'verbose_name_plural': 'Service Areas',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'area_type')},
            },
        ),
    ]
