# Generated by Django 5.2.8 on 2025-12-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='boundary_geojson',
            field=models.JSONField(blank=True, help_text='GeoJSON polygon defining the service area boundary', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='center_point',
            field=models.JSONField(blank=True, help_text='Center point coordinates [lat, lng] for area', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service radius in kilometers (for circular areas)', max_digits=6, null=True),
        ),
    ]
