# Generated by Django 5.2.8 on 2025-12-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_newsletter_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersendlog',
            name='email_address',
            field=models.EmailField(help_text='Email address the newsletter was sent to', max_length=254),
        ),
    ]
