# Generated by Django 5.1.5 on 2025-12-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_newslettercampaign_call_to_action_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for company location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for company location', max_digits=9, null=True),
        ),
    ]
