# Generated by Django 5.2.8 on 2025-12-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_newslettersendlog_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettercampaign',
            name='call_to_action_text',
            field=models.CharField(blank=True, help_text="Text for the call-to-action button (e.g., 'Get a Free Consultation')", max_length=100),
        ),
    ]
