# Generated by Django 5.1.5 on 2025-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_companysettings_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, help_text='Latitude coordinate for company location', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, help_text='Longitude coordinate for company location', max_digits=30, null=True),
        ),
    ]
