# Generated by Django 5.2.8 on 2025-12-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_increase_coordinate_precision_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, help_text='Latitude coordinate for company location', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, help_text='Longitude coordinate for company location', max_digits=30, null=True),
        ),
    ]
