# Generated by Django 5.2.8 on 2026-01-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_companysettings_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='emergency_support_available',
            field=models.BooleanField(default=True, help_text='Whether emergency support is available outside normal hours'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='emergency_support_description',
            field=models.CharField(default='24/7 for active projects', help_text='Description of emergency support availability', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_hours_saturday',
            field=models.CharField(blank=True, default='9:00 AM - 4:00 PM', help_text='Support hours Saturday', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_hours_sunday',
            field=models.CharField(blank=True, default='Closed', help_text='Support hours Sunday', max_length=100),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='support_hours_weekday',
            field=models.CharField(blank=True, default='8:00 AM - 6:00 PM', help_text='Support hours Monday-Friday', max_length=100),
        ),
    ]
