# Generated by Django 5.2.8 on 2026-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_support_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title of the video tutorial', max_length=200)),
                ('description', models.TextField(help_text='Brief description of what the tutorial covers')),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct Video URL'), ('embed', 'Embed Code')], default='youtube', help_text='Type of video hosting platform', max_length=20)),
                ('video_url', models.URLField(help_text='Video URL (YouTube, Vimeo, or direct video link)')),
                ('embed_code', models.TextField(blank=True, help_text='Custom embed code (for embed type)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Custom thumbnail image (optional)', null=True, upload_to='tutorials/')),
                ('duration', models.CharField(blank=True, help_text="Video duration (e.g., '5 minutes')", max_length=20)),
                ('category', models.CharField(blank=True, help_text="Tutorial category (e.g., 'Getting Started', 'Advanced')", max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for filtering', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this tutorial prominently')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tutorial is visible on the help page')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Video Tutorial',
                'verbose_name_plural': 'Video Tutorials',
                'ordering': ['order', '-is_featured', 'title'],
            },
        ),
    ]
