# Generated by Django 5.2.8 on 2026-01-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_increase_coordinate_precision_final'),
        ('core', '0021_add_video_tutorial'),
    ]

    operations = [
    ]
