# Generated by Django 5.2.8 on 2026-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20260110_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, help_text='Latitude coordinate for company location', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, help_text='Longitude coordinate for company location', max_digits=18, null=True),
        ),
    ]
