# Generated by Django 5.2.8 on 2026-01-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_newslettersendlog_email_address'),
        ('core', '0023_alter_companysettings_latitude_and_more'),
    ]

    operations = [
    ]
