# Generated by Django 5.1.7 on 2025-04-14 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='name',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='visitor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
