# Generated by Django 5.1.7 on 2025-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_canonical_url_post_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogbanner',
            name='background_image',
            field=models.ImageField(upload_to='blog/banners/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(upload_to='blog/posts/'),
        ),
    ]
