# Generated by Django 5.0.7 on 2025-09-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_default_lead_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.leadsource'),
        ),
    ]
