# Generated by Django 5.0.7 on 2025-09-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_department_contact_facebook_contact_twitter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
    ]
