# Generated by Django 5.0.7 on 2025-09-10 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_contact_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.leadsource'),
        ),
    ]
