# Generated by Django 5.0.7 on 2025-09-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_opportunity_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100),
        ),
    ]
