# Generated by Django 5.0.7 on 2025-09-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_company_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
