# Generated by Django 5.1.5 on 2025-09-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_document_emailtemplate_emaillog_leadscore_workflow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='access_code',
            field=models.CharField(blank=True, help_text='Access code for virtual meeting', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='action_items',
            field=models.TextField(blank=True, help_text='Specific action items from this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost incurred', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.TextField(blank=True, help_text='Complete address for the activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='agenda',
            field=models.TextField(blank=True, help_text='Activity agenda or topics to be discussed'),
        ),
        migrations.AddField(
            model_name='activity',
            name='calendar_synced',
            field=models.BooleanField(default=False, help_text='Whether synced with external calendar'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.CharField(blank=True, help_text='Activity category for organization', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='decisions_made',
            field=models.TextField(blank=True, help_text='Decisions made during this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='email_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether email reminder was sent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_datetime',
            field=models.DateTimeField(blank=True, help_text='When the activity ends', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost for this activity', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from external calendar system', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='follow_up_date',
            field=models.DateField(blank=True, help_text='Next follow-up date', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='key_discussion_points',
            field=models.TextField(blank=True, help_text='Important points discussed'),
        ),
        migrations.AddField(
            model_name='activity',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='When the last reminder was sent', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, help_text='Meeting location or venue', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='materials_needed',
            field=models.TextField(blank=True, help_text='Any materials or documents needed'),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_id',
            field=models.CharField(blank=True, help_text='Virtual meeting ID', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='meeting_room',
            field=models.CharField(blank=True, help_text='Conference room or virtual meeting room', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='objectives',
            field=models.TextField(blank=True, help_text='Activity goals and objectives'),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users who participated in this activity', related_name='participated_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='preparation_notes',
            field=models.TextField(blank=True, help_text='What needs to be prepared before this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Activity priority level', max_length=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='required_resources',
            field=models.TextField(blank=True, help_text='Resources required for this activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sms_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether SMS reminder was sent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='virtual_meeting_link',
            field=models.URLField(blank=True, help_text='Video conference link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('demo', 'Product Demo'), ('site_visit', 'Site Visit'), ('proposal', 'Proposal Sent'), ('follow_up', 'Follow Up'), ('presentation', 'Presentation'), ('training', 'Training'), ('negotiation', 'Negotiation'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='completed_datetime',
            field=models.DateTimeField(blank=True, help_text='When the activity was actually completed', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed activity description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Activity duration in minutes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='next_steps',
            field=models.TextField(blank=True, help_text='Follow-up actions required'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outcome',
            field=models.TextField(blank=True, help_text='Activity outcome and results'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='scheduled_datetime',
            field=models.DateTimeField(help_text='When the activity is scheduled'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show'), ('postponed', 'Postponed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='subject',
            field=models.CharField(help_text='Brief activity summary', max_length=200),
        ),
    ]
