# Generated by Django 5.1.5 on 2025-09-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_activity_access_code_activity_action_items_and_more'),
    ]

    operations = [
        # Fix charset for all Activity model text fields to support full UTF-8
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY subject VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY subject VARCHAR(200) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY location VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY location VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY address TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY address TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY meeting_room VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY meeting_room VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY virtual_meeting_link VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY virtual_meeting_link VARCHAR(500) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY meeting_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY meeting_id VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY access_code VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY access_code VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY description TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY agenda TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY agenda TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY objectives TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY objectives TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY preparation_notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY preparation_notes TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY materials_needed TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY materials_needed TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY outcome TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY outcome TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY action_items TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY action_items TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY next_steps TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY next_steps TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY notes TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY key_discussion_points TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY key_discussion_points TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY decisions_made TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY decisions_made TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY required_resources TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY required_resources TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY category VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY category VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY tags VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY tags VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_activity MODIFY external_id VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_activity MODIFY external_id VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),

        # Also fix other CRM model text fields
        migrations.RunSQL(
            "ALTER TABLE crm_contact MODIFY notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_contact MODIFY notes TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_company MODIFY notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_company MODIFY notes TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_lead MODIFY description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_lead MODIFY description TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_lead MODIFY notes TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_lead MODIFY notes TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_opportunity MODIFY description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_opportunity MODIFY description TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_opportunity MODIFY next_steps TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_opportunity MODIFY next_steps TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_opportunity MODIFY competition TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_opportunity MODIFY competition TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_campaign MODIFY description TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_campaign MODIFY description TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
        migrations.RunSQL(
            "ALTER TABLE crm_campaign MODIFY message TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE crm_campaign MODIFY message TEXT CHARACTER SET utf8 COLLATE utf8_general_ci;"
        ),
    ]
