# Generated by Django 5.1.5 on 2025-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_fix_activity_description_charset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('lead_nurture', 'Lead Nurturing'), ('follow_up', 'Follow-up'), ('proposal', 'Proposal'), ('thank_you', 'Thank You'), ('rejection', 'Rejection'), ('meeting_request', 'Meeting Request'), ('opportunity_qualification', 'Opportunity Qualification'), ('opportunity_proposal', 'Opportunity Proposal'), ('opportunity_negotiation', 'Opportunity Negotiation'), ('opportunity_closure', 'Opportunity Closure'), ('opportunity_follow_up', 'Opportunity Follow-up'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
    ]
