# Generated by Django 5.1.5 on 2025-08-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.bankaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.currency'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['user', 'timestamp'], name='financial_a_user_id_c7094c_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['content_type', 'object_id'], name='financial_a_content_9d4feb_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['action', 'timestamp'], name='financial_a_action_14d918_idx'),
        ),
        migrations.AddIndex(
            model_name='audittrail',
            index=models.Index(fields=['risk_level', 'timestamp'], name='financial_a_risk_le_141247_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together={('bank_account', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('base_currency', 'target_currency', 'rate_date')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'bank_account'], name='financial_t_transac_31ca14_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='financial_t_referen_0fa515_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'is_reconciled'], name='financial_t_status_64d4d5_idx'),
        ),
    ]
