# Generated by Django 5.0.7 on 2025-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        # Remove the POS Customer model and update Sale to use unified Customer
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey('quotations.Customer', on_delete=models.SET_NULL, null=True, blank=True, related_name='pos_purchases'),
        ),
    ]
