# Generated by Django 5.1.5 on 2025-08-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetreport',
            name='budgets',
            field=models.ManyToManyField(related_name='reports', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='budget.budget'),
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budget'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='budget_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectmilestone'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_type', 'status'], name='budget_budg_budget__26f1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['period_start', 'period_end'], name='budget_budg_period__96286c_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['department', 'fiscal_year'], name='budget_budg_departm_843366_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetapproval',
            unique_together={('budget', 'approval_level')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'name')},
        ),
    ]
