# Generated by Django 5.0.7 on 2025-08-28 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
        ('pos', '0003_auto_20250827_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='pos_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='pos.sale'),
        ),
    ]
