# Generated by Django 5.1.5 on 2025-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_mpesatransaction_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Whether email notification has been sent'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether any notification (SMS/email) has been sent'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notifications were last sent', null=True),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='sms_sent',
            field=models.BooleanField(default=False, help_text='Whether SMS notification has been sent'),
        ),
    ]
