# Generated by Django 5.1.5 on 2025-12-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_mpesatransaction_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, choices=[('dhl', 'DHL Express'), ('fedex', 'FedEx'), ('aramex', 'Aramex'), ('tnt', 'TNT Express'), ('ups', 'UPS'), ('ems', 'EMS'), ('skynet', 'SkyNet'), ('g4s', 'G4S'), ('kipya', 'KIPYA Messenger'), ('sendy', 'Sendy'), ('local', 'Local Courier'), ('other', 'Other')], help_text='Select the shipping company used', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Enter the tracking number provided by the shipping company', max_length=100),
        ),
    ]
