# Generated by Django 5.1.5 on 2025-09-29 06:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='is_typing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='last_typing_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='typing_in_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_users', to='chat.chatroom'),
        ),
    ]
