# Generated by Django 5.2.8 on 2025-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_mentioned_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSystemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Chat System Management',
                'verbose_name_plural': 'Chat System Management',
                'db_table': None,
                'managed': False,
            },
        ),
    ]
