# Generated by Django 5.2.8 on 2026-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatsystemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_auto_join',
            field=models.BooleanField(default=True, help_text='If true, users will be auto-added based on group or general auto-join rules'),
        ),
    ]
