# Generated by Django 5.2.8 on 2026-01-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0008_chatroom_is_auto_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSlug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_slug', to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Slug',
                'verbose_name_plural': 'Group Slugs',
            },
        ),
    ]
