# Generated by Django 5.2.8 on 2026-01-10 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_groupslug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Room',
                'verbose_name_plural': 'Favorite Rooms',
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'room')},
            },
        ),
    ]
